#
# Automatically generated by configure for sol2
#

all:
	cd dll; make 
	cd net; make 
	cd xml; make 
	cd sys; make 

clean:
	cd dll; make clean
	cd net; make clean
	cd xml; make clean
	cd sys; make clean

clobber:
	cd dll; make clobber
	cd net; make clobber
	cd xml; make clobber
	cd sys; make clobber

depend:
	cd dll; make depend
	cd net; make depend
	cd xml; make depend
	cd sys; make depend

install:
	cd dll; make install
	cd net; make install
	cd xml; make install
	cd sys; make install

