#
# Automatically generated by configure for linux
#

all:
	cd sys; make 
	cd xml; make 
	cd net; make 
	cd dll; make 

clean:
	cd sys; make clean
	cd xml; make clean
	cd net; make clean
	cd dll; make clean

clobber:
	cd sys; make clobber
	cd xml; make clobber
	cd net; make clobber
	cd dll; make clobber

depend:
	cd sys; make depend
	cd xml; make depend
	cd net; make depend
	cd dll; make depend

install:
	cd sys; make install
	cd xml; make install
	cd net; make install
	cd dll; make install

