PREFIX	= /usr/local/

ICI	= $(PREFIX)include/ici
FLAVOUR	= sol2
ICI_DEFS= -DCONFIG_FILE='"conf-$(FLAVOUR).h"'

INCS	= -I$(ICI)
DEFS	= $(ICI_DEFS)
CC	= gcc -pipe
OPTIM	= -O
WARN	= -Wall
SYMS	= -g
CODEGEN	= -fpic
CFLAGS	= $(WARN) $(OPTIM) $(SYMS) $(CODEGEN) $(INCS) $(DEFS)

all:	icienv.so

icienv.so:	env.o
	ld -G -o $@ env.o

install: icienv.so
	/usr/ucb/install -c -m 444 icienv.so /usr/local/lib/ici

clean:
	rm -f icienv.so env.o

clobber: clean
	rm -f .depend

depend:
	mkdep $(CFLAGS) env.c
