INSTALL=	install
PREFIX=		/usr/local/
ICIV=		ici3
LIBICI=		$(PREFIX)lib/$(ICIV)

all:

install:\
	$(LIBICI)/$(ICIV)is.ici

$(LIBICI)/$(ICIV)is.ici:	is.ici
	$(INSTALL) -c -m 444 is.ici $@

uninstall:
	rm -f $(LIBICI)/$(ICIV)is.ici


ici.h\
strs.h\
strings.h\
cfuncs.c\
clean\
depend\
clobber:
	@: no need to do anything
